import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter_svg/flutter_svg.dart';
import 'package:image/image.dart' as img;
import 'package:qr/qr.dart';

class QrCodeUtil {
  static bool isSvg(String data) => data.trimLeft().startsWith('<');

  /// Renders whatever the API sends as `qr_code`: either an SVG generated by
  /// the backend or a raw value (e.g. a payment link) that is encoded here.
  static Future<Uint8List?> qrPayloadToPngBytes(
    String qrPayload, {
    int size = 280,
  }) async {
    if (qrPayload.trim().isEmpty) return null;

    if (isSvg(qrPayload)) {
      return svgToPngBytes(qrPayload, size: size);
    }

    return valueToPngBytes(qrPayload, size: size);
  }

  static Future<Uint8List?> svgToPngBytes(
    String svgString, {
    int size = 280,
  }) async {
    if (svgString.trim().isEmpty) return null;

    try {
      final pictureInfo = await vg.loadPicture(
        SvgStringLoader(svgString),
        null,
      );

      final image = await pictureInfo.picture.toImage(size, size);
      final byteData =
          await image.toByteData(format: ui.ImageByteFormat.png);

      pictureInfo.picture.dispose();
      image.dispose();

      return byteData?.buffer.asUint8List();
    } catch (_) {
      return null;
    }
  }

  static Uint8List? valueToPngBytes(String value, {int size = 280}) {
    if (value.trim().isEmpty) return null;

    try {
      final qrCode = QrCode.fromData(
        data: value,
        errorCorrectLevel: QrErrorCorrectLevel.M,
      );
      final qrImage = QrImage(qrCode);

      const quietZone = 4;
      final moduleCount = qrImage.moduleCount + quietZone * 2;
      final scale = size ~/ moduleCount;
      if (scale < 1) return null;

      final imageSize = moduleCount * scale;
      final image = img.Image(width: imageSize, height: imageSize);
      img.fill(image, color: img.ColorRgb8(255, 255, 255));

      for (var row = 0; row < qrImage.moduleCount; row++) {
        for (var col = 0; col < qrImage.moduleCount; col++) {
          if (!qrImage.isDark(row, col)) continue;

          final x = (col + quietZone) * scale;
          final y = (row + quietZone) * scale;
          img.fillRect(
            image,
            x1: x,
            y1: y,
            x2: x + scale - 1,
            y2: y + scale - 1,
            color: img.ColorRgb8(0, 0, 0),
          );
        }
      }

      return Uint8List.fromList(img.encodePng(image));
    } catch (_) {
      return null;
    }
  }
}
